version: "3"
services:
    setup:
        build: .
        depends_on:
          - db
        env_file:
          - env
        command: "rake setup:example"
    db:
        image: mysql:5.7
        env_file:
          - env
        restart: always
    web:
      build: .
      depends_on:
        - db
        - setup
      command: rails s -p 3000 -b '0.0.0.0'
      env_file:
        - env
      ports:
        - "3000:3000"
      depends_on:
        - db        
